name: repository-dispatch-event
on:
  - repository_dispatch

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ§ This job is now running ${{ toJson(github.event.client_payload) }}"
